name: Build SpringBoot app and database

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:
  build:
    name: ğŸ­ Building
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“‘ Checkout code
        uses: actions/checkout@v3

      - name: ğŸ‘¨ğŸ»â€ğŸ’» Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: ğŸ­ Build Project
        run: mvn clean install -DskipTests

      - name: ğŸ“ˆ Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Api Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/igrejapentecostalreformada-api:latest .

      - name: Push Api Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/igrejapentecostalreformada-api:latest

      - name: Build and tag Mysql Image
        run: docker build -t mysql:8.2.0 .

      - name: Push Mysql Image to Docker Hub
        run: docker push mysql:8.2.0


